name: Coverage Badge
description: Badges for test results and code coverage

# Required for publishing to the marketplace:
# Improve your Action by adding labels for icon and color.
branding:
  icon: check-circle
  color: green

runs:
  using: composite
  steps:
    - name: Get Values
      id: get-values
      shell: bash
      run: |
        if [ -f "coverage/coverage-summary.json" ]; then
          COV=$(node -p 't=require(`./coverage/coverage-summary.json`).total,Math.min(...`lines|statements|functions|branches`.split(`|`).map(k=>t[k].pct))')
        elif [ -f "coverage.json" ]; then
          COV=$(python -c 'import json; print(json.load(open("coverage.json"))["totals"]["percent_covered_display"])')
        else
          echo "Error: Neither coverage/coverage-summary.json nor coverage.json found."
          exit 1
        fi
        echo "coverage=$COV" >> $GITHUB_OUTPUT

      # pretend to be still https://github.com/stefanzweifel/git-auto-commit-action/blob/master/action.yml
    - name: Git Config
      shell: bash
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com

    - name: Checkout gh-pages
      uses: actions/checkout@v3
      with:
        ref: gh-pages

    - name: Create Badges
      shell: bash
      env:
        COV: ${{ steps.get-values.outputs.coverage }}
      run: |
        npm i -g badgen-cli
        COLOR=$(node -p '+process.env.COV >= 95 ? `green` : `orange`')
        badgen -j coverage -s $COV% -c $COLOR > $RUNNER_TEMP/coverage.svg

    - name: Deploy Badges
      uses: Wandalen/wretry.action@master
      with:
        attempt_limit: 3
        attempt_delay: 2000
        command: |
          git fetch origin gh-pages
          git reset --hard origin/gh-pages
          mkdir -p badges
          mv $RUNNER_TEMP/coverage.svg badges/
          git add badges/coverage.svg
          git commit -m 'Update badges [skip ci]'
          git push

    # Without this, will get Error:
    # Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/coverage-badge-action/coverage-badge-action/action.yml'.
    # Did you forget to run actions/checkout before running your local action?
    - name: Checkout Back
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
